feat: add support for "addr" query parameter
GoogleCloudPlatform/cloudsql-proxy pull request #1134
Opened 2022-03-14 13:01 UTC by enocom

Callers may now launch the proxy and override the default address on a
per-instance basis.

2022-03-14 15:24 UTC, kurtisvg requested changes

2022-03-14 22:28 UTC, enocom commented on cmd/root.go
> +		if res := strings.Split(a, "?"); len(res) > 1 {
SplitN works nicely here.

2022-03-16 20:08 UTC, enocom commented on internal/proxy/proxy.go
> +	return i.Name
Yeah, probably not. `i.Name` is fine.

2022-03-16 20:44 UTC, kurtisvg approved these changes

2022-03-16 21:14 UTC, merged