feat: add --sqladmin-api-endpoint flag for specifying sqladmin api endpoint
GoogleCloudPlatform/cloudsql-proxy pull request #1251
Opened 2022-06-29 16:30 UTC by hessjcg

Specifies an alternate api endpoint to use for calling the cloud sql admin 
api instead of https://sqladmin.googleapis.com/. This replaces the
This new flag replaces the -host flag in cloudsql-proxy V1.

2022-06-29 17:21 UTC, hessjcg commented on cmd/root.go
> +		// add a trailing '/' if omitted
I prefer this to the v1 behavior, which would exit  code 1 when the url did not have a trailing space.

2022-06-29 17:23 UTC, hessjcg commented on cmd/root_test.go
> +			args: []string{"--api-endpoint-url", "https://user:abc{DEf1=ghi@example.com:5432/db?sslmode=require", "proj:region:inst"},
This url will throw an error from golang url.Parse() because the user:password part is not properly escaped.

2022-06-30 16:12 UTC, kurtisvg requested changes

2022-06-30 17:03 UTC, kurtisvg commented on cmd/root.go
> +	cmd.PersistentFlags().StringVar(&c.conf.ApiEndpointUrl, "api-endpoint-url", "",
Ok, agreed endpoint sounds good.

2022-06-30 17:20 UTC, hessjcg commented on cmd/root.go
> +	cmd.PersistentFlags().StringVar(&c.conf.ApiEndpointUrl, "api-endpoint-url", "",
done.

2022-06-30 21:34 UTC, kurtisvg approved these changes

2022-06-30 21:34 UTC, kurtisvg commented on cmd/root.go
> +			return newBadCommandError(fmt.Sprintf("the value provided for --api-endpoint is not a valid url, %v", conf.ApiEndpointUrl))
```suggestion
			return newBadCommandError(fmt.Sprintf("the value provided for --sqladmin-api-endpoint is not a valid url, %v", conf.ApiEndpointUrl))
```

2022-07-01 15:35 UTC, merged

2022-07-01 16:13 UTC, enocom commented on cmd/root.go
> +		"When set, the proxy uses this url as the API endpoint for all sqladmin API requests. Example: https://sqladmin.googleapis.com")
Let's make it "Cloud SQL Admin API" and use that consistently.

2022-07-01 16:15 UTC, hessjcg commented on cmd/root.go
> +			return newBadCommandError(fmt.Sprintf("the value provided for --api-endpoint is not a valid url, %v", conf.ApiEndpointUrl))
done