chore: ensure IAM user is present before test run
GoogleCloudPlatform/cloudsql-proxy pull request #646
Opened 2021-02-28 22:38 UTC by enocom

Also, add the associated environment variable to .envrc.example.

2021-03-01 18:02 UTC, shubha-rajan approved these changes
LGTM

2021-03-01 20:38 UTC, kurtisvg requested changes
It would be nice to have this only block the tests that need this variable.

2021-03-04 17:51 UTC, shubha-rajan approved these changes

2021-03-04 18:31 UTC, kurtisvg approved these changes

2021-03-04 19:35 UTC, merged